language: r
sudo: true
latex: false
pandoc: false
warnings_are_errors: false
before_install:
- if [[ "$OSTYPE" != "linux-gnu" ]]; then sudo tlmgr install framed titling latexmk;
  fi
- sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng
install: echo "Nothing occurs at installation, only script"
script:
- Rscript install_texlive.R
branches:
- master
- travising
deploy:
  provider: releases
  api_key:
    secure: SmQgcXAwUqZMohFjQRBvADtDHwbVeQckqU19P3ixcSbHFez9/D31tMuNh5hVwIjGGTu/Bl3Kb5jE2CucenI2g/T8qxBBppkynafsT/t3hGlz/xLZwBcgkp34wGmaiUSbYai4y6B0VKrQAIsPhURkYIwsH25/OqFsdvCcvq0SKDQ=
  file: ".travis.yml"
  on:
    repo: lindsayrutter/ggenealogy
